version: '3.8'

services:
  tic-tac-toe: # This is just the service label in YAML 
    build: .
    image: tic-tac-toe:latest
    container_name: nginx-react  # Matches your working setup
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
